### ISSUE TITLE
Unable to Resolve R.drawable.ic_cast_dark

### ISSUE THREAD

**Issue by ACCTFORGH** [oney/react-native-gcm-android#10]
As the title mentioned, the ".setSmallIcon(R.drawable.ic_cast_dark)" method in RNGcmListenerService reports compilation error because ic_cast_dark was not able to be found.  

I am using Android 4.2.2 in Genymotion, Mac El Capital, Android Studio 1.5. 

Appreciate your help!

**Comment by oney** [comment]
Error happen to me too.
Fix in version 0.0.7
https://github.com/oney/react-native-gcm-android/commit/edbb8bfff6585c1f247ac7d0f7b7424761ed6890

**Comment by ACCTFORGH** [comment]
Awesome! Is 0.0.7 available in npm? I did the installation about 2 hours ago and it's still 0.0.6

**Comment by oney** [comment]
Just published 1 hour ago. Please try again.
https://www.npmjs.com/package/react-native-gcm-android
