### ISSUE TITLE
Should onTokenRefresh() be included?

### ISSUE THREAD

**Issue by ACCTFORGH** [oney/react-native-gcm-android#11]
As mentioned in the GCM doc, onTokenRefresh() should be invoked if registration token changed. Currently this method is not included in the package. Should this method be implemented? or the registration token stays same unless manually changed so this method is optional.

GCM doc link: https://developers.google.com/cloud-messaging/android/client?configured=true

Thanks.

**Comment by oney** [comment]
I will recommend doing `requestPermissions ` every time when app starts, and check whether the token changes by yourself.

**Comment by ACCTFORGH** [comment]
Thanks! So the token won't change unless the app is terminated?

Also, one thing I am curious, I first put the requestPermissions() method after the addListeners method as in the instructions but did not get the "register" event captured and didn't see the received token printed in console. However, putting the method before the listeners works. Shouldn't the listeners be lasting and the sequence of requestPermissions() not affect the event being caught by the listeners?

**Comment by oney** [comment]
Hmm.. Token refreshing should be handled better. I will implement it in the future and welcome a PR!

I think the sequence of requestPermissions and listener matters.
I can't figure out why putting requestPermissions() method after the addListeners doesn't work...

**Comment by ACCTFORGH** [comment]
Now, putting the method after the listeners works too. It could be just that it took some time for the app to first time register.
