### ISSUE TITLE
App crashes on Android versions before 5.0 

### ISSUE THREAD

**Issue by jjingrong** [oney/react-native-gcm-android#13]
Compiling and running the app on versions 4.x just crashes the app with a pop-up with an error message of:

    Unfortunately, [APPNAME] has stopped.

Has anyone managed to get around this? This does not occur in versions 5.0 & 6.0.

**Comment by oney** [comment]
Can you run `adb logcat` in terminal to get some logs?

**Comment by jjingrong** [comment]
W/unknown:React(16616): You seem to be running on device. Run 'adb reverse tcp:8081 tcp:8081' to forward the debug server's port to the device.
    I/dalvikvm(16616): Could not find method android.view.View.setAccessibilityLiveRegion, referenced from method com.facebook.react.uimanager.BaseViewManager.setAccessibilityLiveRegion
    W/dalvikvm(16616): VFY: unable to resolve virtual method 17326: Landroid/view/View;.setAccessibilityLiveRegion (I)V
    D/dalvikvm(16616): VFY: replacing opcode 0x6e at 0x0011
    I/dalvikvm(16616): Could not find method android.view.View.setAccessibilityLiveRegion, referenced from method com.facebook.react.uimanager.BaseViewManager.setAccessibilityLiveRegion
    W/dalvikvm(16616): VFY: unable to resolve virtual method 17326: Landroid/view/View;.setAccessibilityLiveRegion (I)V
    D/dalvikvm(16616): VFY: replacing opcode 0x6e at 0x001e
    I/dalvikvm(16616): Could not find method android.view.View.setAccessibilityLiveRegion, referenced from method com.facebook.react.uimanager.BaseViewManager.setAccessibilityLiveRegion
    W/dalvikvm(16616): VFY: unable to resolve virtual method 17326: Landroid/view/View;.setAccessibilityLiveRegion (I)V
    D/dalvikvm(16616): VFY: replacing opcode 0x6e at 0x002b
    W/dalvikvm(16616): VFY: unable to resolve static field 8092 (toolbarStyle) in Lcom/facebook/react/R$attr;
    D/dalvikvm(16616): VFY: replacing opcode 0x60 at 0x000c
    I/dalvikvm(16616): DexOpt: unable to optimize static field ref 0x1f9b at 0x1e in Lcom/facebook/react/views/toolbar/ReactToolbarManager;.getDefaultColors
    I/dalvikvm(16616): DexOpt: unable to optimize static field ref 0x1f9a at 0x23 in Lcom/facebook/react/views/toolbar/ReactToolbarManager;.getDefaultColors
    I/dalvikvm(16616): Could not find method com.facebook.react.views.view.ReactViewGroup.drawableHotspotChanged, referenced from method com.facebook.react.views.view.ReactViewManager.receiveCommand
    W/dalvikvm(16616): VFY: unable to resolve virtual method 25141: Lcom/facebook/react/views/view/ReactViewGroup;.drawableHotspotChanged (FF)V
    D/dalvikvm(16616): VFY: replacing opcode 0x6e at 0x0040
    I/dalvikvm(16616): Could not find method android.webkit.CookieManager.setCookie, referenced from method com.facebook.react.modules.network.ForwardingCookieHandler.addCookieAsync
    W/dalvikvm(16616): VFY: unable to resolve virtual method 17888: Landroid/webkit/CookieManager;.setCookie (Ljava/lang/String;Ljava/lang/String;Landroid/webkit/ValueCallback;)V
    D/dalvikvm(16616): VFY: replacing opcode 0x6e at 0x0005
    I/dalvikvm(16616): Could not find method android.webkit.CookieManager.removeAllCookies, referenced from method com.facebook.react.modules.network.ForwardingCookieHandler.clearCookiesAsync
    W/dalvikvm(16616): VFY: unable to resolve virtual method 17885: Landroid/webkit/CookieManager;.removeAllCookies (Landroid/webkit/ValueCallback;)V
    D/dalvikvm(16616): VFY: replacing opcode 0x6e at 0x0009
    I/dalvikvm(16616): Could not find method android.webkit.CookieManager.flush, referenced from method com.facebook.react.modules.network.ForwardingCookieHandler$CookieSaver.flush
    W/dalvikvm(16616): VFY: unable to resolve virtual method 17881: Landroid/webkit/CookieManager;.flush ()V
    D/dalvikvm(16616): VFY: replacing opcode 0x6e at 0x0006
    E/dalvikvm(16616): Could not find class 'okio.Buffer', referenced from method com.facebook.react.modules.websocket.WebSocketModule.send
    W/dalvikvm(16616): VFY: unable to resolve new-instance 9426 (Lokio/Buffer;) in Lcom/facebook/react/modules/websocket/WebSocketModule;
    D/dalvikvm(16616): VFY: replacing opcode 0x22 at 0x0029
    D/dalvikvm(16616): DexOpt: unable to opt direct call 0xfc76 at 0x2b in Lcom/facebook/react/modules/websocket/WebSocketModule;.send
    I/dalvikvm(16616): Could not find method org.json.JSONObject.wrap, referenced from method com.oney.gcm.GcmModule.convertJSON
    W/dalvikvm(16616): VFY: unable to resolve static method 64852: Lorg/json/JSONObject;.wrap (Ljava/lang/Object;)Ljava/lang/Object;
    D/dalvikvm(16616): VFY: replacing opcode 0x71 at 0x0023
    D/dalvikvm(16616): GC_CONCURRENT freed 638K, 16% free 10379K/12324K, paused 1ms+2ms, total 15ms
    E/        (16616): Unable to load script from assets: index.android.bundle
    E/ReactNative(16616): Got JS Exception: ReferenceError: Can't find variable: require
    E/unknown:React(16616): Exception in native call from JS
    E/unknown:React(16616): com.facebook.react.bridge.JSExecutionException: ReferenceError: Can't find variable: require (line 1 in the generated bundle)
    E/unknown:React(16616): 	at com.facebook.react.bridge.ReactBridge.loadScriptFromAssets(Native Method)
    E/unknown:React(16616): 	at com.facebook.react.bridge.JSBundleLoader$1.loadScript(JSBundleLoader.java:32)
    E/unknown:React(16616): 	at com.facebook.react.bridge.CatalystInstance$2.run(CatalystInstance.java:138)
    E/unknown:React(16616): 	at android.os.Handler.handleCallback(Handler.java:730)
    E/unknown:React(16616): 	at android.os.Handler.dispatchMessage(Handler.java:92)
    E/unknown:React(16616): 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
    E/unknown:React(16616): 	at android.os.Looper.loop(Looper.java:137)
    E/unknown:React(16616): 	at com.facebook.react.bridge.queue.MessageQueueThread$1.run(MessageQueueThread.java:137)
    E/unknown:React(16616): 	at java.lang.Thread.run(Thread.java:841)
    W/dalvikvm(16616): VFY: unable to resolve static field 8133 (Theme_Catalyst_RedBox) in Lcom/facebook/react/R$style;
    D/dalvikvm(16616): VFY: replacing opcode 0x60 at 0x0000
    I/dalvikvm(16616): DexOpt: unable to optimize static field ref 0x1fa5 at 0x0c in Lcom/facebook/react/devsupport/RedBoxDialog;.<init>
    I/dalvikvm(16616): DexOpt: unable to optimize static field ref 0x1fa1 at 0x13 in Lcom/facebook/react/devsupport/RedBoxDialog;.<init>
    I/dalvikvm(16616): DexOpt: unable to optimize static field ref 0x1fa0 at 0x22 in Lcom/facebook/react/devsupport/RedBoxDialog;.<init>
    D/AndroidRuntime(16616): Shutting down VM
    W/dalvikvm(16616): threadid=1: thread exiting with uncaught exception (group=0x41cbf700)
    E/AndroidRuntime(16616): FATAL EXCEPTION: main
    E/AndroidRuntime(16616): java.lang.NoClassDefFoundError: com.facebook.react.R$style
    E/AndroidRuntime(16616): 	at com.facebook.react.devsupport.RedBoxDialog.<init>(RedBoxDialog.java:175)
    E/AndroidRuntime(16616): 	at com.facebook.react.devsupport.DevSupportManager$4.run(DevSupportManager.java:218)
    E/AndroidRuntime(16616): 	at android.os.Handler.handleCallback(Handler.java:730)
    E/AndroidRuntime(16616): 	at android.os.Handler.dispatchMessage(Handler.java:92)
    E/AndroidRuntime(16616): 	at android.os.Looper.loop(Looper.java:137)
    E/AndroidRuntime(16616): 	at android.app.ActivityThread.main(ActivityThread.java:5493)
    E/AndroidRuntime(16616): 	at java.lang.reflect.Method.invokeNative(Native Method)
    E/AndroidRuntime(16616): 	at java.lang.reflect.Method.invoke(Method.java:525)
    E/AndroidRuntime(16616): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1209)
    E/AndroidRuntime(16616): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1025)
    E/AndroidRuntime(16616): 	at dalvik.system.NativeStart.main(Native Method)
    I/SurfaceFlinger( 1986): id=569 Removed ttudypoolmo (4/5)
    I/SurfaceFlinger( 1986): id=569 Removed ttudypoolmo (-2/5)
    I/ActivityManager( 2396): Notify an ApplicationCrash
    I/power   ( 2396): *** release_dvfs_lock : lockType : 1 
    I/dumpstate(16650): begin
    D/SSRMv2:CustomFrequencyManagerService( 2396): releaseDVFSLockLocked : Getting Lock type frm List : DVFS_MIN_LIMIT  frequency : 1200000  uid : 1000  pid : 2396  tag : ACTIVITY_RESUME_BOOSTER@8
    D/SPenGesture( 2396): SpenGestureView: setFocusedWindow
    D/PointerIcon( 2396): setHoveringSpenIconStyle1 pointerType: 10001iconType:1 flag:0
    D/PointerIcon( 2396): setHoveringSpenCustomIcon IconType is same.1
    D/CrashAnrDetector( 2396): processName: com.TestApp_self
    D/CrashAnrDetector( 2396): broadcastEvent : com.TestApp_self data_app_crash
