### ISSUE TITLE
issue after upgrading to version 0.1.0

### ISSUE THREAD

**Issue by jawadrehman** [oney/react-native-gcm-android#16]
FATAL EXCEPTION: IntentService[GcmRegistrationService]
E/AndroidRuntime( 7763): Process: com.voxiosapp, PID: 7763
E/AndroidRuntime( 7763): android.content.res.Resources$NotFoundException: String resource ID #0x0
E/AndroidRuntime( 7763): 	at android.content.res.Resources.getText(Resources.java:306)
E/AndroidRuntime( 7763): 	at android.content.res.Resources.getString(Resources.java:392)
E/AndroidRuntime( 7763): 	at android.content.Context.getString(Context.java:383)
E/AndroidRuntime( 7763): 	at com.oney.gcm.GcmRegistrationService.onHandleIntent(GcmRegistrationService.java:30)
E/AndroidRuntime( 7763): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/AndroidRuntime( 7763): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 7763): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 7763): 	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by oney** [comment]
I guess you have file `google-services.json` in `android/app` directory, right?

**Comment by jawadrehman** [comment]
your latest update seems to have sorted this particular issue
