### ISSUE TITLE
Android GCM permission request crashes app

### ISSUE THREAD

**Issue by AdamGorkoz** [oney/react-native-gcm-android#23]
Hi all ,

I've followed the setup guide and installed all that is needed but i've encountered a problem where when this line runs : GcmAndroid.requestPermissions();
the application crashes.

any ideas ?

**Comment by oney** [comment]
Please run `adb logcat` in terminal to get some logs when the app crashes

**Comment by AdamGorkoz** [comment]
Got this log : 
![image](https://cloud.githubusercontent.com/assets/10440278/12221335/59829b36-b79f-11e5-8013-3b4b8b882e65.png)

Cant really make anything of it

**Comment by oney** [comment]
You have `android/app/google-services.json` file, right?

**Comment by AdamGorkoz** [comment]
I was missing that file , but now i have a different error while running react-native run-android : 

![image](https://cloud.githubusercontent.com/assets/10440278/12221363/b55895a4-b7a0-11e5-8140-a525f8324295.png)

and in the packager : 
![image](https://cloud.githubusercontent.com/assets/10440278/12221364/be10310c-b7a0-11e5-8d08-733d68f638a7.png)

**Comment by oney** [comment]
Please try clean the project
```shell
cd android
./gradlew clean
```

**Comment by AdamGorkoz** [comment]
Ok that did the trick , But i'm not getting the token though , Should this work on an emulator (using genymotion) ?

**Comment by oney** [comment]
No, it doesn't work on Genymotion if you don't install Google Play service on it.
https://github.com/oney/react-native-gcm-android/issues/21#issuecomment-169751762

**Comment by oney** [comment]
If you still have problem, please reopen it. Thanks!
