### ISSUE TITLE
Missing modules in react-native packager

### ISSUE THREAD

**Issue by herby** [oney/react-native-gcm-android#4]
This is piece of `react-native start` output:

```
[1:57:09 PM] <START> request:/index.android.map?platform=android&dev=true
[1:57:09 PM] <START> find dependencies
Unable to resolve module Map from D:\Herby\Work\foo\bar\node_modules\react-native-gcm-android\index.android.js
Unable to resolve module invariant from D:\Herby\Work\foo\bar\node_modules\react-native-gcm-android\index.android.js
[1:57:09 PM] <END>   find dependencies (318ms)
[1:57:09 PM] <START> transform
transforming [========================================] 100% 417/418
```

after which the package is stuck.

I see you do `require('Map')` and `require('invariant')` in `index.android.js`, but there is no trace of them in `package.json`...

**Comment by oney** [comment]
It seems that requiring JS from React Native core doesn't work after 0.14.0. I am not familiar with Node.js require system, if I am wrong, please correct me.
Now I publish 0.0.4 version of `react-native-gcm-android`, please try testing whether it works.

**Comment by oney** [comment]
The bug was fixed. I close this issue now. If having any problem, be free to reopen it.
