### ISSUE TITLE
Notification not receiving from server but GCM response in success??

### ISSUE THREAD

**Issue by blazeprasanna** [oney/react-native-gcm-android#48]
Am not getting notification from server.

**Comment by samcarlosimpres** [comment]
Open android/app/src/main/AndroidManifest.xml, change com.oney.gcm.RNGcmListenerService to io.neson.react.notification.GCMNotificationListenerService.

**Comment by blazeprasanna** [comment]
@samcarlosimpres thanks for the reply.I solved the problem... Notification not received because of device .I changed the device and got notification.
