### ISSUE TITLE
Error: 'GcmAndroid.launchNotification internal', undefined

### ISSUE THREAD

**Issue by zj-lin-zj** [oney/react-native-gcm-android#57]
I understand the there's a previous post https://github.com/oney/react-native-gcm-android/issues/30 about this error and the code worked later. However, in my case, even after I restart the app, it still shows error of 'GcmAndroid.launchNotification internal', undefined. My env specs:

RN 0.24
Android 4.4.2 on Genymotion
Latest version of this module and the notifications module

Many thanks!

**Comment by GedoonS** [comment]
That might not be an error. It's just the line 
console.log('GcmAndroid.launchNotification internal', GcmAndroid.launchNotification);
inreact-native-gcm-android/index.android.js

which runs every time it starts. It's undefined, if the system didn't start it with a notification.
