### ISSUE TITLE
Use global `Map`

### ISSUE THREAD

**Issue by herby** [oney/react-native-gcm-android#6]
Do not `require` it from internal structure of `react-native`, as explained in facebook/react-native#4396.

**Comment by herby** [comment]
This should help to solve #4 in a correct way, making it work with npm3 as well.

**Comment by oney** [comment]
Thanks.
So modify codes below?
```
var Map = require('Map');
```

**Comment by herby** [comment]
Howard Yang wrote:
> Thanks.
> So modify codes below?
>
> |var Map = require('Map');
> |

just remove it. `Map` is global and you can just use it.

**Comment by oney** [comment]
OK. I see.

**Comment by oney** [comment]
We can get it on version 0.0.6 with npm now. Thanks for searching solution!

**Comment by herby** [comment]
It helps me as well ;-)

Howard Yang wrote:

**Comment by herby** [comment]
Fixed by b3c773b1c4ac99301872079ec26622461baeafe0
