### ISSUE TITLE
Do not use `invariant` at all

### ISSUE THREAD

**Issue by herby** [oney/react-native-gcm-android#7]
It is purely internal to `react-native` and should not be used by outside code, as explained in facebook/react-native#4397.

**Comment by herby** [comment]
This should help to solve #4 in a correct way, making it work with npm3 as well.

**Comment by oney** [comment]
I will remove `invariant`

**Comment by herby** [comment]
If you want to enforce it somehow, you can still `if (...check wrong condition...) throw new Error("Invariant not true.");` or something...

Howard Yang wrote:

**Comment by oney** [comment]
Will verify arguments in the future.

**Comment by herby** [comment]
Removed in b3c773b1c4ac99301872079ec26622461baeafe0, may be closed, maybe?

**Comment by oney** [comment]
@herby It should be closed!

**Comment by oney** [comment]
By the way, we have [invariant](https://www.npmjs.com/package/invariant) package in npm now.
