### ISSUE TITLE
GCM Dependency Update Suggested

### ISSUE THREAD

**Issue by ACCTFORGH** [oney/react-native-gcm-android#9]
The current google play dependencies include the whole package of gms while only the gcm part is needed. The gms whole package is big and could reach the method quantity limit of Android. That is, change the gms dependency to the one below

compile "com.google.android.gms:play-services-gcm:8.1.0" instead of 

compile "com.google.android.gms:play-services:8.1.0"

**Comment by oney** [comment]
Available in version 0.0.7. Thanks!
https://github.com/oney/react-native-gcm-android/commit/cf8fadcf67f6ceb72650f8c0f48d3e522669bf6a
